import './nav/browser';
import './typer/browser';
import './templater/browser';
import './modal/browser';
import './form/browser';
import './toaster/browser';
import './i18n/browser';
import './storage/browser';
import './store/browser';